/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.c                                             */
/*  DATE        :Sat, May 12, 2018                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :H8S/2329F                                             */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  



#include "iodefine.h"
#ifdef __cplusplus
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif


void HardwareSetup(void)
{
/*
  TPU.TSTR.BYTE = 0;
  TPU.TSTR.BIT.CST5 = 1;
  TPU.TSTR.BIT.CST4 = 1;
  TPU.TSTR.BIT.CST3 = 1;
  TPU.TSTR.BIT.CST2 = 1;
  TPU.TSTR.BIT.CST1 = 1;
  TPU.TSTR.BIT.CST0 = 1;
  TPU.TSYR.BYTE = 0;
  TPU.TSYR.BIT.SYNC5 = 1;
  TPU.TSYR.BIT.SYNC4 = 1;
  TPU.TSYR.BIT.SYNC3 = 1;
  TPU.TSYR.BIT.SYNC2 = 1;
  TPU.TSYR.BIT.SYNC1 = 1;
  TPU.TSYR.BIT.SYNC0 = 1;
*/
}
