/***********************************************************************/
/*                                                                     */
/*  FILE        :lowsrc.c                                              */
/*  DATE        :Tue, May 08, 2018                                     */
/*  DESCRIPTION :Program of I/O Stream                                 */
/*  CPU TYPE    :H8S/                                                  */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  



#include <string.h>
#include <no_float.h>
#include <stdio.h>
#include <stddef.h>
#include "typedefine.h"
#include "lowsrc.h"

#if __STDC_VERSION__ == 199901L
#ifndef _STDIO_C89
/* file number */
#define STDIN  0                    /* Standard input (console)        */
#define STDOUT 1                    /* Standard output (console)       */
#define STDERR 2                    /* Standard error output (console) */

#define FLMIN  0                    /* Minimum file number     */
#define _MOPENR	0x1
#define _MOPENW	0x2
#define _MOPENA	0x4
#define _MTRUNC	0x8
#define _MCREAT	0x10
#define _MBIN	0x20
#define _MEXCL	0x40
#define _MALBUF	0x40
#define _MALFIL	0x80
#define _MEOF	0x100
#define _MERR	0x200
#define _MLBF	0x400
#define _MNBF	0x800
#define _MREAD	0x1000
#define _MWRITE	0x2000
#define _MBYTE	0x4000
#define _MWIDE	0x8000
/* File Flags */
#define O_RDONLY 0x0001 /* Read only                                       */
#define O_WRONLY 0x0002 /* Write only                                      */
#define O_RDWR   0x0004 /* Both read and Write                             */
#define O_CREAT  0x0008 /* A file is created if it is not existed          */
#define O_TRUNC  0x0010 /* The file size is changed to 0 if it is existed. */
#define O_APPEND 0x0020 /* The position is set for next reading/writing    */
                        /* 0: Top of the file 1: End of file               */

/* Special character code */
#define CR 0x0d                     /* Carriage return */
#define LF 0x0a                     /* Line feed       */

const int _nfiles = IOSTREAM;  /* The number of files for input/output files */
char flmod[IOSTREAM];          /* The location for the mode of opened file.  */

unsigned char sml_buf[IOSTREAM];

#define FPATH_STDIN     "C:\\stdin"
#define FPATH_STDOUT    "C:\\stdout"
#define FPATH_STDERR    "C:\\stderr"

/* H8 Normal mode ,SH and RX */
#if defined( __2000N__ ) || defined( __2600N__ ) || defined( __300HN__ ) || defined( _SH ) || defined( __RX )
/* Output one character to standard output */
extern void charput(char);
/* Input one character from standard input */
extern char charget(void);
/* Output one character to the file        */
extern char fcharput(char, unsigned char);
/* Input one character from the file       */
extern char fcharget(char*, unsigned char);
/* Open the file */
extern char fileopen(char*, unsigned char, unsigned char*);
/* Close the file */
extern char fileclose(unsigned char);
/* Move the file offset */
extern char fpseek(unsigned char, long, unsigned char);
/* Get the file offset */
extern char fptell(unsigned char, long*);

/* H8 Advanced mode */
#elif defined( __2000A__ ) || defined( __2600A__ ) || defined( __300HA__ ) || defined( __H8SXN__ ) || defined( __H8SXA__ ) || defined( __H8SXM__ ) || defined( __H8SXX__ )
/* Output one character to standard output */
extern void charput(char);
/* Input one character from standard input */
extern char charget(void);
/* Output one character to the file        */
extern char fcharput(char, unsigned char);
/* Input one character from the file       */
extern char fcharget(char*, unsigned char);
/* Open the file */
/* Specified as the number of register which stored paramter is 3 */
extern char __regparam3 fileopen(char*, unsigned char, unsigned char*);
/* Close the file */
extern char fileclose(unsigned char);
/* Move the file offset */
extern char fpseek(unsigned char, long, unsigned char);
/* Get the file offset */
extern char fptell(unsigned char, long*);

/* H8300 and H8300L */
#elif defined( __300__ ) || defined( __300L__ )
/* Output one character to standard output */
extern void charput(char);
/* Input one character from standard input */
extern char charget(void);
/* Output one character to the file        */
extern char fcharput(char, unsigned char);
/* Input one character from the file       */
extern char fcharget(char*, unsigned char);
/* Open the file */
/* Specified as the number of register which stored paramter is 3 */
extern char __regparam3 fileopen(char*, unsigned char, unsigned char*);
/* Close the file */
extern char fileclose(unsigned char);
/* Move the file offset */
/* Move the file offset */
extern char __regparam3 fpseek(unsigned char, long, unsigned char);
/* Get the file offset */
extern char fptell(unsigned char, long*);
#endif

#include <stdio.h>
FILE *_Files[IOSTREAM]; // structure for FILE
char *env_list[] = {            // Array for environment variables(**environ)
    "ENV1=temp01",
    "ENV2=temp02",
    "ENV9=end",
    '\0'                        // Terminal for environment variables
};

char **environ = env_list;

/****************************************************************************/
/* _INIT_IOLIB                                                              */
/*  Initialize C library Functions, if necessary.                           */
/*  Define USES_SIMIO on Assembler Option.                                  */
/****************************************************************************/
void _INIT_IOLIB( void )
{
    /* A file for standard input/output is opened or created. Each FILE     */
    /* structure members are initialized by the library. Each _Buf member   */
    /* in it is re-set the end of buffer pointer.                           */

    /* Standard Input File                                                  */
    if( freopen( FPATH_STDIN, "r", stdin ) == NULL )
        stdin->_Mode = 0xffff;  /* Not allow the access if it fails to open */
    stdin->_Mode |= _MOPENR;            /* Read only attribute              */
    stdin->_Mode |= _MNBF;              /* Non-buffering for data           */
    stdin->_Bend = stdin->_Buf + 1;  /* Re-set pointer to the end of buffer */

    /* Standard Output File                                                 */
    if( freopen( FPATH_STDOUT, "w", stdout ) == NULL ) 
        stdout->_Mode = 0xffff; /* Not allow the access if it fails to open */
    stdout->_Mode |= _MNBF;             /* Non-buffering for data           */
    stdout->_Bend = stdout->_Buf + 1;/* Re-set pointer to the end of buffer */
    
    /* Standard Error File                                                  */
    if( freopen( FPATH_STDERR, "w", stderr ) == NULL )
        stderr->_Mode = 0xffff; /* Not allow the access if it fails to open */
    stderr->_Mode |= _MNBF;             /* Non-buffering for data           */
    stderr->_Bend = stderr->_Buf + 1;/* Re-set pointer to the end of buffer */
}

/****************************************************************************/
/* _CLOSEALL                                                                */
/****************************************************************************/
void _CLOSEALL( void )
{
    int i;

    for( i=0; i < _nfiles; i++ )
    {
        /* Checks if the file is opened or not                               */
        if( _Files[i]->_Mode & (_MOPENR | _MOPENW | _MOPENA ) )
        fclose( _Files[i] );    /* Closes the file                           */
    }
}

/**************************************************************************/
/*       open:file open                                                   */
/*          Return value:File number (Pass)                               */
/*                       -1          (Failure)                            */
/**************************************************************************/
int open(char *name,                        /* File name                      */
     int  mode,                         /* Open mode                      */
     int  flg)                          /* Open flag                      */
{


    if( strcmp( name, FPATH_STDIN ) == 0 )      /* Standard Input file?   */
    {
        if( ( mode & O_RDONLY ) == 0 ) return -1;
        flmod[STDIN] = mode;
        return STDIN;
    }
    else if( strcmp( name, FPATH_STDOUT ) == 0 )/* Standard Output file?  */
    {
        if( ( mode & O_WRONLY ) == 0 ) return -1;
        flmod[STDOUT] = mode;
        return STDOUT;
    }
    else if(strcmp(name, FPATH_STDERR ) == 0 )  /* Standard Error file?   */
    {
        if( ( mode & O_WRONLY ) == 0 ) return -1;
        flmod[STDERR] = mode;
        return STDERR;
    }
    else return -1;                             /*Others                  */
}

int close( int fileno )
{
    return 1;
}

/**************************************************************************/
/* write:Data write                                                       */
/*  Return value:Number of write characters (Pass)                        */
/*               -1                         (Failure)                     */
/**************************************************************************/
int write(int  fileno,                  /* File number                    */
      char *buf,                        /* The address of destination buffer */
      int  count)                       /* The number of chacter to write */
{
    unsigned int    i;                  /* A variable for counter         */
    char             c;                 /* An output character            */

    /* Checking the mode of file , output each character                  */
    /* Checking the attribute for Write-Only, Read-Only or Read-Write     */
    if(flmod[fileno]&O_WRONLY || flmod[fileno]&O_RDWR)
    {
        if( fileno == STDIN ) return -1;            /* Standard Input     */
        else if( (fileno == STDOUT) || (fileno == STDERR) ) 
			                                    /* Standard Error/output   */
        {
            for( i = count; i > 0; --i )
            {
                c = *buf++;
                charput(c);
            }
            return count;        /*Return the number of written characters */
        }
        else return -1;                  /* Incorrect file number          */
    }
    else return -1;                      /* An error                       */
}

int read( int fileno, char *buf, unsigned int count )
{
	   unsigned int i;

       /* Checking the file mode with the file number, each character is input and stored the buffer */

       if((flmod[fileno]&_MOPENR) || (flmod[fileno]&O_RDWR)){
             for(i = count; i > 0u; i--){
                   *buf = charget();
                   if(*buf==CR){              /* Replace the new line character */
                         *buf = LF;
                   }
                   buf++;
             }
             return count;
       }
       else {
             return -1;
       }
}

long lseek( short fileno, short offset, short base )
{
    return -1L;
}

#define _DONE
#endif
#endif

#ifdef _DONE
#undef _DONE
#else
_SINT open(_SBYTE *name, _SINT mode, _SINT flg);
_SINT close(_SINT fileno);
_SINT read(_SINT fileno, _SBYTE *buf, _UINT count);
_SINT write(_SINT fileno, _SBYTE *buf, _UINT count);
_SDWORD lseek(_SINT fileno, _SDWORD offset, _SINT base);
void _INIT_IOLIB(void);
void _CLOSEALL(void);


/* file number */

#define STDIN  0        /* Standard input (console)        */
#define STDOUT 1        /* Standard output (console)       */
#define STDERR 2        /* Standard error output (console) */

#define FLMIN  0               /* Minimum file number     */
#define FLMAX  (IOSTREAM-1)    /* Maximum number of files */

/* file flag */

#define O_RDONLY 0x0001     /* Read only           */
#define O_WRONLY 0x0002     /* Write only          */
#define O_RDWR   0x0004     /* Both read and Write */

/* special character code */

#define CR 0x0d     /* Carriage return */
#define LF 0x0a     /* Line feed       */

const _SINT _nfiles = IOSTREAM;
struct _iobuf _iob[IOSTREAM];
_UBYTE sml_buf[IOSTREAM];


/***************************************************************************/
/* Declaration of reference function                                       */
/* Reference to assembly program in which the simulator debugger inputs or */
/* outputs characters to the console                                       */
/***************************************************************************/
extern void charput(_SBYTE);     /* One character output */
extern _SBYTE charget(void);     /* One character input  */

/*****************************************************************************/
/* Definition of static variables:                                           */
/* Definition of static variables used in low-level interface routines       */
/*****************************************************************************/
_SBYTE flmod[IOSTREAM];             /* Open file mode specification area */

/***************************************************************************/
/*    open: file open                                                      */
/*          Return value: File number (Pass)                               */
/*                        -1          (Failure)                            */
/***************************************************************************/
_SINT open(_SBYTE *name,         /* File name           */
     _SINT mode,                 /* File mode           */
     _SINT flg)                  /* Unused              */
{
       /* Checks mode depending on file name and returns file numbers */

       if(strcmp((const char *) name,"stdin")==0){         /* Standard input file    */
             if((mode&O_RDONLY)==0){
                      return -1;
             }
             flmod[STDIN] = mode;
             return STDIN;
       }

       else if(strcmp((const char *) name,"stdout")==0){   /* Standard output file   */
             if((mode&O_WRONLY)==0){
                      return -1;
             }
             flmod[STDOUT] = mode;
             return STDOUT;
       }

       else if(strcmp((const char *) name,"stderr")==0){	/* Standard error file    */
             if((mode&O_WRONLY)==0){
                      return -1;
             }
             flmod[STDERR] = mode;
             return STDERR;
       }

       else {
             return -1;		/* Error */
       }
}

/*****************************************************************************/
/*   close: File close                                                       */
/*          Return value: 0  (Pass)                                          */
/*                        -1 (Failure)                                       */
/*****************************************************************************/
_SINT close(_SINT fileno)        /* File number */
{
       if((fileno<FLMIN) || (FLMAX<fileno)){     /* File number range check */
             return -1;
       }
       flmod[fileno] = 0;        /* File mode reset */
       return 0;
}

/*****************************************************************************/
/* read: Data read                                                           */
/*       Return value: Number of read characters (Pass)                      */
/*                     -1                         (Failure)                  */
/*****************************************************************************/
_SINT read(_SINT fileno,         /* File number                */
     _SBYTE *buf,                /* Destination buffer address */
     _UINT count)                /* Number of read characters  */
{
       _UINT i;

       /* Checks mode according to file no. and stores each character in buffer */

       if((flmod[fileno]&O_RDONLY) || (flmod[fileno]&O_RDWR)){
             for(i = count; i > 0u; i--){
                   *buf = charget();
                   if(*buf==CR){        /* Line feed character replacement */
                         *buf = LF;
                   }
                   buf++;
             }
             return count;
       }
       else {
             return -1;
       }
}
 
/****************************************************************************/
/* write: Data write                                                        */
/*        Return value: Number of write characters (Pass)                   */
/*                      -1                         (Failure)                */
/****************************************************************************/
_SINT write(_SINT fileno,        /* File number */
     _SBYTE *buf,                /* Destination buffer address */
     _UINT count)                /* Number of write characters */
{
       _UINT i;
       _SBYTE c;

       /* Checks mode according to file no. and outputs each character */

       if((flmod[fileno]&O_WRONLY) || (flmod[fileno]&O_RDWR)){
             for(i = count; i > 0u; i--){
                   c = *buf++;
                   charput(c);
             }
             return count;
       }
       else {
             return -1;
       }
}

/*****************************************************************************/
/* lseek: Definition of file read/write position                             */
/*      Return value: Offset from the top of file read/write position (Pass) */
/*                    -1              (Failure)                              */
/*        (lseek is not supported in the console input/output)               */
/*****************************************************************************/
_SDWORD lseek(int fileno,        /* File number */
       _SDWORD offset,           /* Read/write position */
       _SINT base)               /* Origin of offset */
{
       return -1L;
}

/****************************************************************************/
/* _INIT_IOLIB                                                              */
/****************************************************************************/
void _INIT_IOLIB(void)
{
       FILE *fp;

       for(fp = _iob; fp < _iob+_nfiles; fp++){  // Set initial values for FILE-type data
             fp->_bufptr = NULL;
             fp->_bufcnt = 0L;
             fp->_buflen = 0L;
             fp->_bufbase = NULL;
             fp->_ioflag1 = 0;
             fp->_ioflag2 = 0;
             fp->_iofd = 0;
       }

       if(freopen("stdin", "r", stdin)==NULL){      // Open standard I/O file
             stdin->_ioflag1 = 0xff;                // Forbid file access if open fails
       }
       stdin->_ioflag1 |= _IOUNBUF;                 // Set without data buffering

       if(freopen("stdout", "w", stdout)==NULL){    // Open standard I/O file
             stdout->_ioflag1 = 0xff;               // Forbid file access if open fails
       }
       stdout->_ioflag1 |= _IOUNBUF;                // Set without data buffering

       if(freopen("stderr", "w", stderr)==NULL){    // Open standard error file
             stderr->_ioflag1 = 0xff;               // Forbid file access if open fails
       }
       stderr->_ioflag1 |= _IOUNBUF;                // Set without data buffering
}

/****************************************************************************/
/* _CLOSEALL                                                                */
/****************************************************************************/
void _CLOSEALL(void)
{
       _SINT i;

       for(i = 0; i < _nfiles; i++){
             // Check to see whether the file is open or not
             if(_iob[i]._ioflag1 & (_IOREAD | _IOWRITE | _IORW )){
                     fclose(& _iob[i]);      // Close the file
             }
       }
}
#endif