/***********************************************************************/
/*                                                                     */
/*  FILE        :lowsrc.h                                              */
/*  DATE        :Tue, May 08, 2018                                     */
/*  DESCRIPTION :Header file of I/O Stream file                        */
/*  CPU TYPE    :H8S/                                                  */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
/*Number of I/O Stream*/
#define IOSTREAM 3
