/***********************************************************************/
/*                                                                     */
/*  FILE        :resetprg.c                                            */
/*  DATE        :Sat, May 12, 2018                                     */
/*  DESCRIPTION :Reset Program                                         */
/*  CPU TYPE    :H8S/2329F                                             */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  


#include	<machine.h>
#include	<_h_c_lib.h>
//#include	<stddef.h>					// Remove the comment when you use errno
//#include 	<stdlib.h>					// Remove the comment when you use rand()
#include	"typedefine.h"
#include	"stacksct.h"

extern void main(void);
__entry(vect=0) void PowerON_Reset(void);
//__interrupt(vect=1) void Manual_Reset(void);

extern void _INIT_IOLIB(void);
extern void _CLOSEALL(void);

//extern void srand(_UINT);		// Remove the comment when you use rand()
//extern _SBYTE *_s1ptr;				// Remove the comment when you use strtok()
		
#ifdef __cplusplus				// Use Hardware Setup
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif


#pragma section ResetPRG

__entry(vect=0) void PowerON_Reset(void)
{ 
	 set_imask_ccr((_UBYTE)1);
	_INITSCT();

#ifdef USE_IO
	_INIT_IOLIB();					// Enable I/O in the application(both SIM I/O and hardware I/O)
#endif

//	errno=0;						// Remove the comment when you use errno
//	srand((_UINT)1);					// Remove the comment when you use rand()
		
//	HardwareSetup();				// Use Hardware Setup
	set_imask_ccr((_UBYTE)0);

	main();

#ifdef USE_IO
	_CLOSEALL();					// Close I/O in the application(both SIM I/O andhardware I/O)
#endif	

	sleep();
}

//__interrupt(vect=1) void Manual_Reset(void)	// Remove the comment when you use Manual Reset
//{
//} 
