/***********************************************************************/
/*                                                                     */
/*  FILE        :sbrk.h                                                */
/*  DATE        :Sat, May 12, 2018                                     */
/*  DESCRIPTION :Header file of sbrk file                              */
/*  CPU TYPE    :H8S/2329F                                             */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
/* size of area managed by sbrk */
#define HEAPSIZE 0x52a0
