/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Sat, May 12, 2018                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :H8S/2329F                                             */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
#pragma stacksize 0x1000        /* Do not modify this line. */
