/***********************************************************************/
/*                                                                     */
/*  FILE        :test80.c                                              */
/*  DATE        :Sat, May 12, 2018                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8S/2329F                                             */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include <stdio.h>


int main()
{
	printf("hello\n");
	return 0;
}
